import { ImageSourcePropType } from 'react-native';

// Static require() calls — React Native requires these at build time
const ingredientImages: Record<string, ImageSourcePropType> = {
  // Vegetables
  tomato: require('../../assets/images/ingredients/tomato.png'),
  onion: require('../../assets/images/ingredients/onion.png'),
  garlic: require('../../assets/images/ingredients/garlic.png'),
  pepper: require('../../assets/images/ingredients/pepper.png'),
  'bell-pepper': require('../../assets/images/ingredients/bell-pepper.png'),
  mushroom: require('../../assets/images/ingredients/mushroom.png'),
  potato: require('../../assets/images/ingredients/potato.png'),
  'sweet-potato': require('../../assets/images/ingredients/sweet-potato.png'),
  carrot: require('../../assets/images/ingredients/carrot.png'),
  broccoli: require('../../assets/images/ingredients/broccoli.png'),
  cauliflower: require('../../assets/images/ingredients/cauliflower.png'),
  corn: require('../../assets/images/ingredients/corn.png'),
  avocado: require('../../assets/images/ingredients/avocado.png'),
  cucumber: require('../../assets/images/ingredients/cucumber.png'),
  'leafy-greens': require('../../assets/images/ingredients/leafy-greens.png'),
  celery: require('../../assets/images/ingredients/celery.png'),
  asparagus: require('../../assets/images/ingredients/asparagus.png'),
  zucchini: require('../../assets/images/ingredients/zucchini.png'),
  eggplant: require('../../assets/images/ingredients/eggplant.png'),
  peas: require('../../assets/images/ingredients/peas.png'),
  'green-beans': require('../../assets/images/ingredients/green-beans.png'),
  radish: require('../../assets/images/ingredients/radish.png'),
  beet: require('../../assets/images/ingredients/beet.png'),
  cabbage: require('../../assets/images/ingredients/cabbage.png'),
  kale: require('../../assets/images/ingredients/kale.png'),

  // Fruits
  lemon: require('../../assets/images/ingredients/lemon.png'),
  lime: require('../../assets/images/ingredients/lime.png'),
  apple: require('../../assets/images/ingredients/apple.png'),
  banana: require('../../assets/images/ingredients/banana.png'),
  strawberry: require('../../assets/images/ingredients/strawberry.png'),
  blueberry: require('../../assets/images/ingredients/blueberry.png'),
  raspberry: require('../../assets/images/ingredients/raspberry.png'),
  cranberry: require('../../assets/images/ingredients/cranberry.png'),
  coconut: require('../../assets/images/ingredients/coconut.png'),
  pineapple: require('../../assets/images/ingredients/pineapple.png'),
  peach: require('../../assets/images/ingredients/peach.png'),
  cherry: require('../../assets/images/ingredients/cherry.png'),
  grape: require('../../assets/images/ingredients/grape.png'),
  orange: require('../../assets/images/ingredients/orange.png'),
  mango: require('../../assets/images/ingredients/mango.png'),
  watermelon: require('../../assets/images/ingredients/watermelon.png'),
  pear: require('../../assets/images/ingredients/pear.png'),
  kiwi: require('../../assets/images/ingredients/kiwi.png'),
  papaya: require('../../assets/images/ingredients/papaya.png'),
  plum: require('../../assets/images/ingredients/plum.png'),
  fig: require('../../assets/images/ingredients/fig.png'),
  pomegranate: require('../../assets/images/ingredients/pomegranate.png'),

  // Dairy
  egg: require('../../assets/images/ingredients/egg.png'),
  butter: require('../../assets/images/ingredients/butter.png'),
  milk: require('../../assets/images/ingredients/milk.png'),
  cheese: require('../../assets/images/ingredients/cheese.png'),
  cream: require('../../assets/images/ingredients/cream.png'),
  yogurt: require('../../assets/images/ingredients/yogurt.png'),
  'sour-cream': require('../../assets/images/ingredients/sour-cream.png'),
  'cream-cheese': require('../../assets/images/ingredients/cream-cheese.png'),

  // Proteins
  chicken: require('../../assets/images/ingredients/chicken.png'),
  beef: require('../../assets/images/ingredients/beef.png'),
  bacon: require('../../assets/images/ingredients/bacon.png'),
  turkey: require('../../assets/images/ingredients/turkey.png'),
  lamb: require('../../assets/images/ingredients/lamb.png'),
  sausage: require('../../assets/images/ingredients/sausage.png'),
  tofu: require('../../assets/images/ingredients/tofu.png'),

  // Seafood
  shrimp: require('../../assets/images/ingredients/shrimp.png'),
  salmon: require('../../assets/images/ingredients/salmon.png'),
  tuna: require('../../assets/images/ingredients/tuna.png'),
  crab: require('../../assets/images/ingredients/crab.png'),
  lobster: require('../../assets/images/ingredients/lobster.png'),

  // Grains & starches
  rice: require('../../assets/images/ingredients/rice.png'),
  bread: require('../../assets/images/ingredients/bread.png'),
  pasta: require('../../assets/images/ingredients/pasta.png'),
  flour: require('../../assets/images/ingredients/flour.png'),
  oats: require('../../assets/images/ingredients/oats.png'),
  quinoa: require('../../assets/images/ingredients/quinoa.png'),
  tortilla: require('../../assets/images/ingredients/tortilla.png'),
  cornstarch: require('../../assets/images/ingredients/cornstarch.png'),

  // Herbs & spices
  herbs: require('../../assets/images/ingredients/herbs.png'),
  ginger: require('../../assets/images/ingredients/ginger.png'),
  cinnamon: require('../../assets/images/ingredients/cinnamon.png'),
  cumin: require('../../assets/images/ingredients/cumin.png'),
  paprika: require('../../assets/images/ingredients/paprika.png'),
  oregano: require('../../assets/images/ingredients/oregano.png'),
  thyme: require('../../assets/images/ingredients/thyme.png'),
  rosemary: require('../../assets/images/ingredients/rosemary.png'),
  nutmeg: require('../../assets/images/ingredients/nutmeg.png'),
  turmeric: require('../../assets/images/ingredients/turmeric.png'),
  'black-pepper': require('../../assets/images/ingredients/black-pepper.png'),
  vanilla: require('../../assets/images/ingredients/vanilla.png'),

  // Condiments & sauces
  'soy-sauce': require('../../assets/images/ingredients/soy-sauce.png'),
  vinegar: require('../../assets/images/ingredients/vinegar.png'),
  mustard: require('../../assets/images/ingredients/mustard.png'),
  ketchup: require('../../assets/images/ingredients/ketchup.png'),
  mayonnaise: require('../../assets/images/ingredients/mayonnaise.png'),
  'hot-sauce': require('../../assets/images/ingredients/hot-sauce.png'),

  // Sweeteners & pantry
  sugar: require('../../assets/images/ingredients/sugar.png'),
  salt: require('../../assets/images/ingredients/salt.png'),
  honey: require('../../assets/images/ingredients/honey.png'),
  'maple-syrup': require('../../assets/images/ingredients/maple-syrup.png'),
  chocolate: require('../../assets/images/ingredients/chocolate.png'),
  'olive-oil': require('../../assets/images/ingredients/olive-oil.png'),
  water: require('../../assets/images/ingredients/water.png'),
  wine: require('../../assets/images/ingredients/wine.png'),
  'coconut-milk': require('../../assets/images/ingredients/coconut-milk.png'),
  broth: require('../../assets/images/ingredients/broth.png'),
  'baking-powder': require('../../assets/images/ingredients/baking-powder.png'),
  yeast: require('../../assets/images/ingredients/yeast.png'),

  // Nuts & seeds
  almond: require('../../assets/images/ingredients/almond.png'),
  walnut: require('../../assets/images/ingredients/walnut.png'),
  peanut: require('../../assets/images/ingredients/peanut.png'),
  sesame: require('../../assets/images/ingredients/sesame.png'),

  // Legumes
  lentils: require('../../assets/images/ingredients/lentils.png'),
  chickpeas: require('../../assets/images/ingredients/chickpeas.png'),
  'black-beans': require('../../assets/images/ingredients/black-beans.png'),
};

const categoryImages: Record<string, ImageSourcePropType> = {
  produce: require('../../assets/images/ingredients/cat-produce.png'),
  vegetables: require('../../assets/images/ingredients/cat-produce.png'),
  fruits: require('../../assets/images/ingredients/apple.png'),
  dairy: require('../../assets/images/ingredients/cat-dairy.png'),
  meat: require('../../assets/images/ingredients/cat-meat.png'),
  poultry: require('../../assets/images/ingredients/cat-poultry.png'),
  seafood: require('../../assets/images/ingredients/cat-seafood.png'),
  fish: require('../../assets/images/ingredients/cat-seafood.png'),
  pantry: require('../../assets/images/ingredients/cat-pantry.png'),
  grains: require('../../assets/images/ingredients/cat-grains.png'),
  pasta: require('../../assets/images/ingredients/pasta.png'),
  spices: require('../../assets/images/ingredients/cat-spices.png'),
  herbs: require('../../assets/images/ingredients/herbs.png'),
  oils: require('../../assets/images/ingredients/olive-oil.png'),
  condiments: require('../../assets/images/ingredients/cat-condiments.png'),
  sauces: require('../../assets/images/ingredients/cat-sauces.png'),
  baking: require('../../assets/images/ingredients/cat-baking.png'),
  beverages: require('../../assets/images/ingredients/cat-beverages.png'),
  frozen: require('../../assets/images/ingredients/cat-frozen.png'),
  snacks: require('../../assets/images/ingredients/cat-snacks.png'),
  nuts: require('../../assets/images/ingredients/cat-nuts.png'),
  legumes: require('../../assets/images/ingredients/cat-legumes.png'),
  other: require('../../assets/images/ingredients/cat-other.png'),
};

const defaultImage = require('../../assets/images/ingredients/cat-other.png');

// Maps name keywords to their image key (includes singular/plural and aliases)
const nameToImageKey: Record<string, string> = {
  // Vegetables
  tomato: 'tomato',
  tomatoes: 'tomato',
  onion: 'onion',
  onions: 'onion',
  'green onion': 'onion',
  'green onions': 'onion',
  shallot: 'onion',
  shallots: 'onion',
  garlic: 'garlic',
  pepper: 'pepper',
  peppers: 'pepper',
  chili: 'pepper',
  chilli: 'pepper',
  jalapeno: 'pepper',
  'bell pepper': 'bell-pepper',
  'bell peppers': 'bell-pepper',
  capsicum: 'bell-pepper',
  mushroom: 'mushroom',
  mushrooms: 'mushroom',
  potato: 'potato',
  potatoes: 'potato',
  'sweet potato': 'sweet-potato',
  'sweet potatoes': 'sweet-potato',
  yam: 'sweet-potato',
  yams: 'sweet-potato',
  carrot: 'carrot',
  carrots: 'carrot',
  broccoli: 'broccoli',
  cauliflower: 'cauliflower',
  corn: 'corn',
  avocado: 'avocado',
  avocados: 'avocado',
  cucumber: 'cucumber',
  cucumbers: 'cucumber',
  lettuce: 'leafy-greens',
  spinach: 'leafy-greens',
  arugula: 'leafy-greens',
  'mixed greens': 'leafy-greens',
  celery: 'celery',
  asparagus: 'asparagus',
  zucchini: 'zucchini',
  courgette: 'zucchini',
  eggplant: 'eggplant',
  aubergine: 'eggplant',
  peas: 'peas',
  pea: 'peas',
  'green peas': 'peas',
  'snap peas': 'peas',
  'green bean': 'green-beans',
  'green beans': 'green-beans',
  'string bean': 'green-beans',
  'string beans': 'green-beans',
  radish: 'radish',
  radishes: 'radish',
  beet: 'beet',
  beets: 'beet',
  beetroot: 'beet',
  cabbage: 'cabbage',
  kale: 'kale',

  // Fruits
  lemon: 'lemon',
  lemons: 'lemon',
  lime: 'lime',
  limes: 'lime',
  apple: 'apple',
  apples: 'apple',
  banana: 'banana',
  bananas: 'banana',
  strawberry: 'strawberry',
  strawberries: 'strawberry',
  blueberry: 'blueberry',
  blueberries: 'blueberry',
  raspberry: 'raspberry',
  raspberries: 'raspberry',
  cranberry: 'cranberry',
  cranberries: 'cranberry',
  coconut: 'coconut',
  pineapple: 'pineapple',
  peach: 'peach',
  peaches: 'peach',
  cherry: 'cherry',
  cherries: 'cherry',
  grape: 'grape',
  grapes: 'grape',
  orange: 'orange',
  oranges: 'orange',
  mango: 'mango',
  mangoes: 'mango',
  mangos: 'mango',
  watermelon: 'watermelon',
  pear: 'pear',
  pears: 'pear',
  kiwi: 'kiwi',
  papaya: 'papaya',
  plum: 'plum',
  plums: 'plum',
  fig: 'fig',
  figs: 'fig',
  pomegranate: 'pomegranate',

  // Dairy & eggs
  egg: 'egg',
  eggs: 'egg',
  butter: 'butter',
  milk: 'milk',
  'whole milk': 'milk',
  buttermilk: 'milk',
  cheese: 'cheese',
  mozzarella: 'cheese',
  parmesan: 'cheese',
  cheddar: 'cheese',
  gruyere: 'cheese',
  gouda: 'cheese',
  feta: 'cheese',
  ricotta: 'cheese',
  cream: 'cream',
  'heavy cream': 'cream',
  'whipping cream': 'cream',
  'double cream': 'cream',
  yogurt: 'yogurt',
  yoghurt: 'yogurt',
  'greek yogurt': 'yogurt',
  'sour cream': 'sour-cream',
  'cream cheese': 'cream-cheese',

  // Proteins
  chicken: 'chicken',
  beef: 'beef',
  steak: 'beef',
  'ground beef': 'beef',
  mince: 'beef',
  pork: 'bacon',
  bacon: 'bacon',
  pancetta: 'bacon',
  prosciutto: 'bacon',
  turkey: 'turkey',
  lamb: 'lamb',
  sausage: 'sausage',
  sausages: 'sausage',
  chorizo: 'sausage',
  salami: 'sausage',
  tofu: 'tofu',
  tempeh: 'tofu',

  // Seafood
  shrimp: 'shrimp',
  prawns: 'shrimp',
  salmon: 'salmon',
  tuna: 'tuna',
  cod: 'tuna',
  tilapia: 'tuna',
  crab: 'crab',
  lobster: 'lobster',

  // Grains & starches
  rice: 'rice',
  'basmati rice': 'rice',
  'jasmine rice': 'rice',
  'brown rice': 'rice',
  bread: 'bread',
  'bread crumbs': 'bread',
  breadcrumbs: 'bread',
  spaghetti: 'pasta',
  pasta: 'pasta',
  noodles: 'pasta',
  penne: 'pasta',
  linguine: 'pasta',
  fettuccine: 'pasta',
  macaroni: 'pasta',
  rigatoni: 'pasta',
  lasagna: 'pasta',
  flour: 'flour',
  'all-purpose flour': 'flour',
  'bread flour': 'flour',
  oats: 'oats',
  oatmeal: 'oats',
  'rolled oats': 'oats',
  quinoa: 'quinoa',
  couscous: 'quinoa',
  bulgur: 'quinoa',
  tortilla: 'tortilla',
  tortillas: 'tortilla',
  wrap: 'tortilla',
  wraps: 'tortilla',
  pita: 'tortilla',
  cornstarch: 'cornstarch',
  'corn starch': 'cornstarch',

  // Herbs fresh
  basil: 'herbs',
  parsley: 'herbs',
  cilantro: 'herbs',
  coriander: 'herbs',
  dill: 'herbs',
  mint: 'herbs',
  chives: 'herbs',
  tarragon: 'herbs',

  // Spices
  ginger: 'ginger',
  cinnamon: 'cinnamon',
  cumin: 'cumin',
  paprika: 'paprika',
  'smoked paprika': 'paprika',
  oregano: 'oregano',
  thyme: 'thyme',
  rosemary: 'rosemary',
  nutmeg: 'nutmeg',
  turmeric: 'turmeric',
  'black pepper': 'black-pepper',
  peppercorn: 'black-pepper',
  peppercorns: 'black-pepper',
  vanilla: 'vanilla',
  'vanilla extract': 'vanilla',

  // Condiments & sauces
  'soy sauce': 'soy-sauce',
  vinegar: 'vinegar',
  'balsamic vinegar': 'vinegar',
  'apple cider vinegar': 'vinegar',
  'rice vinegar': 'vinegar',
  'white vinegar': 'vinegar',
  mustard: 'mustard',
  'dijon mustard': 'mustard',
  ketchup: 'ketchup',
  mayonnaise: 'mayonnaise',
  mayo: 'mayonnaise',
  'hot sauce': 'hot-sauce',
  sriracha: 'hot-sauce',
  tabasco: 'hot-sauce',

  // Sweeteners & pantry
  sugar: 'sugar',
  'brown sugar': 'sugar',
  'powdered sugar': 'sugar',
  salt: 'salt',
  'sea salt': 'salt',
  'kosher salt': 'salt',
  honey: 'honey',
  'maple syrup': 'maple-syrup',
  chocolate: 'chocolate',
  'dark chocolate': 'chocolate',
  'chocolate chips': 'chocolate',
  cocoa: 'chocolate',
  'cocoa powder': 'chocolate',
  olive: 'olive-oil',
  'olive oil': 'olive-oil',
  'extra virgin olive oil': 'olive-oil',
  oil: 'olive-oil',
  'vegetable oil': 'olive-oil',
  'canola oil': 'olive-oil',
  'sesame oil': 'olive-oil',
  water: 'water',
  wine: 'wine',
  'red wine': 'wine',
  'white wine': 'wine',
  'coconut milk': 'coconut-milk',
  'coconut cream': 'coconut-milk',
  broth: 'broth',
  stock: 'broth',
  'chicken broth': 'broth',
  'chicken stock': 'broth',
  'beef broth': 'broth',
  'vegetable broth': 'broth',
  'baking powder': 'baking-powder',
  'baking soda': 'baking-powder',
  'bicarbonate of soda': 'baking-powder',
  yeast: 'yeast',

  // Nuts & seeds
  almond: 'almond',
  almonds: 'almond',
  walnut: 'walnut',
  walnuts: 'walnut',
  peanut: 'peanut',
  peanuts: 'peanut',
  'peanut butter': 'peanut',
  sesame: 'sesame',
  'sesame seeds': 'sesame',
  cashew: 'almond',
  cashews: 'almond',
  pecan: 'walnut',
  pecans: 'walnut',
  'pine nuts': 'almond',
  pistachio: 'almond',
  pistachios: 'almond',

  // Legumes
  lentil: 'lentils',
  lentils: 'lentils',
  'red lentils': 'lentils',
  chickpea: 'chickpeas',
  chickpeas: 'chickpeas',
  'garbanzo beans': 'chickpeas',
  'black bean': 'black-beans',
  'black beans': 'black-beans',
  'kidney beans': 'black-beans',
  'white beans': 'black-beans',
  'cannellini beans': 'black-beans',
  beans: 'black-beans',
};

export function getIngredientImage(
  name: string,
  category?: string,
): ImageSourcePropType {
  const lowerName = name.toLowerCase();

  // Exact name match
  if (nameToImageKey[lowerName]) {
    return ingredientImages[nameToImageKey[lowerName]];
  }

  // Substring match
  for (const [key, imageKey] of Object.entries(nameToImageKey)) {
    if (lowerName.includes(key)) {
      return ingredientImages[imageKey];
    }
  }

  // Category fallback
  if (category) {
    const lowerCategory = category.toLowerCase();
    if (categoryImages[lowerCategory]) {
      return categoryImages[lowerCategory];
    }
  }

  return defaultImage;
}
